language: python
matrix:
  include:
    - python: 3.7-dev
      dist: xenial
      sudo: true

# This build should not be triggered by tags
if: tags IS blank


# Anything in install that returns a nonzero exit code will
# flunk the build and immediately stop. It's sorta like having
# set -e enabled in bash.

before_script:
  - export BUILD_BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST, BUILD_BRANCH=$BUILD_BRANCH"
  - make -C monitoring-data install
  
# script always run to completion (set +e). All of these code checks are must haves
# in a modern Python project.
script:
  - make -C monitoring-data docker-build
  - make -C monitoring-data check-style
after_failure:
  - reports-publisher

after_success:
  - reports-publisher
  - make -C monitoring-data docker-publish