- defaultTab: nodes
  description: |-
    Traffic metrics etl \
      sudo docker run --rm -v /home/bnbiuser/secrets/pulse_auth:/app/pulse-secret \
        -v /home/bnbiuser/secrets/dw_db:/app/db-secret \
        -e APP_PULSE_SECRET=/app/pulse-secret \
        -e APP_DB_SECRET=/app/db-secret \
        containers.mpi-internal.com/yapo/data-pulse-traffic-metrics:fix_traffic-inconsistency
  executionEnabled: true
  group: GLOBAL-METRIC
  loglevel: DEBUG
  name: Buyer - Traffic metrics
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      successOnEmptyNodeFilter: false
      threadcount: '1'
    filter: 'name: dockerhost'
  nodesSelectedByDefault: true
  notifyAvgDurationThreshold: null
  scheduleEnabled: false
  sequence:
    commands:
    - script: |-
      sudo docker pull containers.mpi-internal.com/yapo/data-pulse-traffic-metrics:fix_traffic-inconsistency
        
      sudo docker run --rm -v /home/bnbiuser/secrets/pulse_auth:/app/pulse-secret \
                      -v /home/bnbiuser/secrets/dw_db:/app/db-secret \
                      -e APP_PULSE_SECRET=/app/pulse-secret \
                      -e APP_DB_SECRET=/app/db-secret \
                      containers.mpi-internal.com/yapo/data-pulse-traffic-metrics:fix_traffic-inconsistency
    keepgoing: false
    strategy: node-first
  timeZone: America/Santiago
