- defaultTab: nodes
  description: |-
        sudo docker run -v /home/bnbiuser/secrets/pulse_auth:/app/pulse-secret \
                        -v /home/bnbiuser/secrets/dw_db:/app/db-secret \
                        -e APP_PULSE_SECRET=/app/pulse-secret \
                        -e APP_DB_SECRET=/app/db-secret \
                        containers.mpi-internal.com/yapo/data-pulse-traffic-metrics:latest
  executionEnabled: true
  group: GLOBAL-METRIC
  loglevel: DEBUG
  name: Buyer - Traffic metrics
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      successOnEmptyNodeFilter: false
      threadcount: '1'
    filter: 'name: dockerhost'
  nodesSelectedByDefault: true
  notification:
    onfailure:
      email:
        recipients: data_team@adevinta.com
        subject: ${job.execid} ${execution.status} ${job.name}
    onstart:
      email:
        recipients: data_team@adevinta.com
        subject: ${job.execid} ${execution.status} ${job.name}
    onsuccess:
      email:
        recipients: data_team@adevinta.com
        subject: ${job.execid} ${execution.status} ${job.name}
  notifyAvgDurationThreshold: null
  schedule:
    month: '*'
    time:
      hour: '05'
      minute: '0'
      seconds: '0'
    weekday:
      day: '*'
    year: '*'
  scheduleEnabled: true
  sequence:
    commands:
    - script: |-
        sudo docker pull containers.mpi-internal.com/yapo/data-pulse-traffic-metrics:latest
        
        sudo docker run -v /home/bnbiuser/secrets/pulse_auth:/app/pulse-secret \
                        -v /home/bnbiuser/secrets/dw_db:/app/db-secret \
                        -e APP_PULSE_SECRET=/app/pulse-secret \
                        -e APP_DB_SECRET=/app/db-secret \
                        containers.mpi-internal.com/yapo/data-pulse-traffic-metrics:latest
    keepgoing: false
    strategy: node-first
  timeZone: America/Santiago
